baseurl = "http://tuts.emrealadag.com"
languageCode = "en-us"
title = "Tutorials by Ahmet Emre Aladağ"
theme = "greyshade"

[author]
name = "Ahmet Emre Aladağ"
email = "aladagemre@gmail.com"
website = "http://www.emrealadag.com"

[taxonomies]
category = "categories"
tag = "tags"

[params]
description = "Tutorials by Ahmet Emre Aladağ."
subscribe_rss = "/index.xml"
subscribe_email = ""
menu_home_text = "Tutorial Home"
menu_about_url = "http://www.emrealadag.com"
menu_about_text = "Personal Site"
menu_archives_text = "Archives"

# social links
googleplus_user = "ahmetemrealadag"
twitter_user = "aladagemre"
github_user = "aladagemre"
stackoverflow_user = "aladagemre"
linkedin_user = "ahmet-emre-aladag"
pinterest_user = "aladagemre"
quora_user = "aladagemre"
instagram_user = "aladag.emre"


facebook_like = true
twitter_tweet_button = true
google_plus_one = "true"


# follow links
twitter_follow = true

disqus_short_name = "emrealadag"
disqus_show_comment_count = false
google_analytics_tracking_id = "UA-2553826-1"
